load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "AppProvisionerReconciller",
    main_class = "com.scalingcontroller.AppProvisionerReconciller",
    runtime_deps = [
        "//src/main/java/com/scalingcontroller:operator",
    ],
)
